const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
const FETCH_IS_LOGIN = 'FETCH_IS_LOGIN';
const FETCH_IS_LOGOUT = 'FETCH_IS_LOGOUT';

export {
    FETCH_USERS_REQUEST,
    FETCH_USERS_SUCCESS,
    FETCH_USERS_ERROR,
    FETCH_IS_LOGIN,
    FETCH_IS_LOGOUT,
}